- hosts: suse_rancher
  become: true
  tasks:
  - name: "Install Docker"
    yum:
      name: "docker"
      state: present
      
  - name: Ensure service is enabled
    command: sudo systemctl start docker
      
  - name: "install pip3"
    yum:
      name: "python3-pip"
      state: present
      
  - name: "docker library install"
    pip:
      name: "docker"
      executable: pip3

  - name: "setup suse rancher"
    docker_container:
      name: "suse-rancher-con"
      image: "rancher/rancher:latest"
      ports:
      - "80:80"
      - "443:443"
      restart_policy: unless-stopped
      privileged: yes
