- hosts: suse_rancher
  become: true
  tasks:
  - name: "Install Docker"
    yum:
      name: "docker"
      state: present

  - name: "Start and Enable Docker Service"
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: "install pip3"
    yum:
      name: "python3-pip"
      state: present
      
  - name: "docker library install"
    pip:
      name: "dockerd"
      executable: pip3

  - name: "setup suse rancher"
    docker_container:
      name: "suse-rancher-con"
      image: "rancher/rancher"
      ports:
      - "80:80"
      - "443:443"
      restart_policy: unless-stopped
      privileged: yes
