---
- hosts: all
  become: yes
  tasks:
   - name: Install defined packages
     yum:
       name: "{{ item }}"
       state: present
   - name: starting services 
     service:
       name: "{{ item }}"
       state: started
     with_items:
       - httpd
       - mysql
       - vsftpd
